using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Threading;
using System.Threading.Tasks;

namespace Deckle.Transcription.Setup;

// ── NativeRuntime ────────────────────────────────────────────────────────────
//
// **Single source of truth** for the whisper.cpp native runtime. This is
// the only module in the app that names libwhisper.dll, ggml-*.dll, and
// the MinGW C++ runtime DLLs the Vulkan backend links against. Anything
// else that needs to detect, install, or copy these files goes through
// the methods exposed here — no parallel knowledge of the catalog.
//
// Concrete consumers:
//   • NativeMethods.ResolveNativeLibrary uses EntryDll to build the
//     absolute path it hands to NativeLibrary.TryLoad. Once libwhisper
//     loads, Windows resolves its ggml-*.dll dependencies from the same
//     directory automatically — they don't need to be listed by name on
//     the load side.
//   • The first-run wizard provisions the runtime through three paths:
//       1. Auto-download via CurrentBundle.Url + InstallFromZipAsync.
//       2. Local Browse via CopyFromFolder (offline / dev fallback).
//       3. Out-of-band populate via scripts/lib/setup-assets.ps1 / publish
//          script + manual copy.
//     IsInstalled and GetMissing report status across all three paths.
//
// What's intentionally NOT here:
//   • The "libwhisper" P/Invoke key (the string in [DllImport("libwhisper")]).
//     C# requires a constant literal in DllImport attributes, so every
//     P/Invoke in NativeMethods stays hard-coded with that string. The
//     EntryDll constant below matches it ("libwhisper" + ".dll") so the
//     two stay in sync by convention.
//   • Catalog of speech models (Whisper .bin, Silero VAD). Lives in
//     Setup/SpeechModels — different lifecycle, different trust boundary
//     (download from HuggingFace vs redistribute via our own release).
public static class NativeRuntime
{
    // Filename used by ResolveNativeLibrary as the entry point. Must match
    // the literal "libwhisper" in [DllImport(...)] attributes plus ".dll".
    public const string EntryDll = "libwhisper.dll";

    // Every DLL the runtime needs to be present in NativeDirectory. The
    // first five are whisper.cpp's Vulkan build output (libwhisper +
    // ggml backends); the last three are the MinGW C++ runtime libraries
    // the Vulkan ggml-vulkan.dll links against. Windows resolves them
    // automatically once they sit alongside libwhisper.dll.
    //
    // Mirrored on the PowerShell side in scripts/lib/setup-assets.ps1 and
    // scripts/lib/publish-native-runtime.ps1 — any divergence is a bug.
    public static IReadOnlyList<string> RequiredDllNames { get; } = new[]
    {
        EntryDll,
        "ggml.dll",
        "ggml-base.dll",
        "ggml-cpu.dll",
        "ggml-vulkan.dll",
        "libgcc_s_seh-1.dll",
        "libstdc++-6.dll",
        "libwinpthread-1.dll",
    };

    // ── Versioned bundle published to the Deckle GitHub Releases ─────────────

    // Single source of truth for the runtime bundle the wizard auto-downloads.
    // Url + Sha256 + SizeBytes drive Downloader.DownloadAsync; DisplayName is
    // surfaced verbatim in the wizard's progress UI.
    //
    // Lifecycle: regenerated by scripts/lib/publish-native-runtime.ps1 whenever
    // whisper.cpp upstream is bumped or the toolchain changes. The script
    // emits a paste-ready snippet for CurrentBundle on stdout — the SHA256
    // is non-deterministic across rebuilds (zip timestamps), so it must be
    // updated together with the URL and SizeBytes after every publish.
    public sealed record NativeRuntimeBundle(
        string Version,
        string Url,
        string Sha256,
        long SizeBytes,
        string DisplayName);

    public static NativeRuntimeBundle CurrentBundle { get; } = new(
        Version:     "1.0.0",
        Url:         "https://github.com/PelopeeNoire/deckle/releases/download/native-v1.0.0/deckle-native-1.0.0.zip",
        Sha256:      "c7304be24ccca1255b2bdd6d10609d87fe806590704a07e20b9af233b1d6e4cc",
        SizeBytes:   19_131_111L,
        DisplayName: "Whisper.cpp + Vulkan runtime");

    // True while CurrentBundle.Url has not been wired to the actual published
    // release. Consumers (notably ChoicesPage and InstallingPage) treat this
    // as "auto-download disabled" and force the manual Browse... fallback.
    // This keeps the app shippable end-to-end even when the URL is still a
    // placeholder, instead of failing loudly at the first wizard run.
    public static bool BundleUrlIsPlaceholder =>
        CurrentBundle.Url.Contains("PLACEHOLDER", StringComparison.OrdinalIgnoreCase);

    // ── Status + install paths ───────────────────────────────────────────────

    // True when libwhisper.dll is present in NativeDirectory — the canonical
    // install location populated by any of the three provisioning paths.
    //
    // The full catalog isn't checked file-by-file: if the entry point
    // is there, NativeMethods.SetDllImportResolver loads it and Windows
    // resolves the transitive ggml-*.dll dependencies from the same
    // directory automatically. A missing transitive dep would surface
    // as a DllNotFoundException on the first whisper_* call — clear
    // enough without a redundant catalog sweep here.
    public static bool IsInstalled() =>
        File.Exists(Path.Combine(AppPaths.NativeDirectory, EntryDll));

    // Copies every catalog DLL found in `sourcePath` into NativeDirectory,
    // overwriting existing files. Returns the count of DLLs actually copied.
    // Files in the source folder that are NOT in the catalog are ignored —
    // keeps NativeDirectory tidy when the user points at a build folder
    // that contains other artifacts.
    //
    // Used by the wizard's "Browse for folder..." flow. Idempotent:
    // calling twice with the same source overwrites the same files.
    public static int CopyFromFolder(string sourcePath)
    {
        Directory.CreateDirectory(AppPaths.NativeDirectory);
        int copied = 0;
        foreach (string name in RequiredDllNames)
        {
            string from = Path.Combine(sourcePath, name);
            if (!File.Exists(from)) continue;
            string to = Path.Combine(AppPaths.NativeDirectory, name);
            File.Copy(from, to, overwrite: true);
            copied++;
        }
        return copied;
    }

    // Extracts every catalog entry from `zipPath` into NativeDirectory.
    // Used by the wizard's auto-download path: Downloader.DownloadAsync
    // streams the zip to a .partial file, verifies SHA-256, and on success
    // hands the file to this method.
    //
    // Two safety properties:
    //
    //   1. Catalog filter — only entries whose name matches RequiredDllNames
    //      are extracted. Any other entry in the zip (PROVENANCE.txt,
    //      SHA256SUMS, hypothetical malicious filename, path traversal
    //      attempt) is ignored. The catalog is the trust boundary.
    //
    //   2. Atomic publish per file — each DLL is extracted to <name>.partial,
    //      then File.Move(..., overwrite: true) renames it to its final
    //      name. An interrupted extract leaves a .partial the next attempt
    //      overwrites; the final filename never appears half-written under
    //      a process that may already be loading it.
    //
    // Returns the count of catalog DLLs actually present in the zip and
    // extracted. The caller compares against RequiredDllNames.Count to
    // detect a malformed bundle.
    public static async Task<int> InstallFromZipAsync(
        string zipPath,
        CancellationToken ct)
    {
        Directory.CreateDirectory(AppPaths.NativeDirectory);

        using var archive = ZipFile.OpenRead(zipPath);
        int extracted = 0;

        foreach (string name in RequiredDllNames)
        {
            ct.ThrowIfCancellationRequested();

            ZipArchiveEntry? entry = archive.GetEntry(name);
            if (entry is null) continue;

            string finalPath   = Path.Combine(AppPaths.NativeDirectory, name);
            string partialPath = finalPath + ".partial";

            try
            {
                using (Stream src = entry.Open())
                using (var dst = new FileStream(
                    partialPath,
                    FileMode.Create, FileAccess.Write, FileShare.None,
                    bufferSize: 81920, useAsync: true))
                {
                    await src.CopyToAsync(dst, ct).ConfigureAwait(false);
                }
                File.Move(partialPath, finalPath, overwrite: true);
                extracted++;
            }
            catch
            {
                try { if (File.Exists(partialPath)) File.Delete(partialPath); }
                catch { /* best-effort */ }
                throw;
            }
        }

        return extracted;
    }

    // Reports which catalog DLLs are missing from NativeDirectory. Empty
    // result = fully installed. Used by the wizard to surface a precise
    // status ("4 of 8 files installed") and by diagnostics surfaces.
    public static IReadOnlyList<string> GetMissing()
    {
        var missing = new List<string>();
        foreach (string name in RequiredDllNames)
        {
            string path = Path.Combine(AppPaths.NativeDirectory, name);
            if (!File.Exists(path)) missing.Add(name);
        }
        return missing;
    }
}
