<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Deckle.Diagnostics.Telemetry</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Deckle.Diagnostics\Deckle.Diagnostics.csproj" />
    <ProjectReference Include="..\Deckle.Core\Deckle.Core.csproj" />
  </ItemGroup>
</Project>
