<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Deckle.TestSupport</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Deckle.Diagnostics\Deckle.Diagnostics.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="WindowsAppSdkModuleInitializer.cs" />
  </ItemGroup>
</Project>
