using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Deckle.Autocorrect;

namespace Deckle.Autocorrect.Probe;

// Joins the consented physical-key timing stream to transactions generated by
// the current packaged-base autocorrect composition. Text stays in memory: the
// report contains only aggregate counters, distributions, and source/artifact
// fingerprints. The result is a temporal replay counterfactual, not evidence
// that the historical screen or current personal configuration was identical.
internal static class AnticipationTransactionJoinCommand
{
    private static readonly double[] DecisionBudgetsMilliseconds =
        [50.0, 100.0, 150.0, 393.1803, 537.5866];
    private static readonly int[] TriggerDelaysMilliseconds = [0, 50, 100];
    private static readonly char[] TerminalBranches = ['.', '?', '!', '…'];

    public static int Run(ProbeArguments parsed)
    {
        string? dataDirectory = AutocorrectBenchmarkCommand.ResolveDataDirectory();
        if (dataDirectory is null)
        {
            Console.Error.WriteLine("Packaged autocorrect data was not found beside the probe output.");
            return 1;
        }

        AnticipationTransactionJoinFileReport report;
        try
        {
            report = AnalyzeFile(parsed.StreamPath, parsed.StreamBytes, dataDirectory);
        }
        catch (Exception error)
        {
            // Never serialize exception messages: a parsing or suffix failure can
            // carry private input. The closed type name is sufficient to diagnose
            // the technical class from the retained local raw run.
            Console.Error.WriteLine(error.GetType().Name);
            return 1;
        }

        Console.WriteLine(JsonSerializer.Serialize(report, new JsonSerializerOptions
        {
            PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower,
        }));
        return report.TechnicallyValid ? 0 : 3;
    }

    internal static AnticipationTransactionJoinFileReport AnalyzeFile(
        string path,
        long requestedBytes,
        string dataDirectory)
    {
        var before = new FileInfo(path);
        long analyzedBytes = requestedBytes > 0 ? requestedBytes : before.Length;
        byte[] prefixBefore = ReadPrefix(path, analyzedBytes);
        bool lineBoundary = prefixBefore.Length == 0
            || prefixBefore[^1] is (byte)'\n' or (byte)'\r';
        BenchmarkKnowledge knowledge = BenchmarkKnowledge.Load(dataDirectory);
        AutocorrectPolicySet policies = AutocorrectPolicySet.Create(
            knowledge.French,
            knowledge.English,
            knowledge.AccentIndex,
            knowledge.Context,
            verbs: knowledge.Verbs);
        AnticipationTransactionJoinAnalysis analysis = Analyze(
            ReadLines(prefixBefore),
            knowledge,
            policies);

        byte[] prefixAfter = ReadPrefix(path, analyzedBytes);
        TypingStreamPrefixIdentity identity = CreatePrefixIdentity(
            prefixBefore,
            prefixAfter,
            lineBoundary);
        var after = new FileInfo(path);
        JoinValidity validity = ClassifyValidity(
            identity.Stable,
            analysis.ParsedRuns,
            analysis.MalformedRuns,
            analysis.FirstTerminalGestures,
            analysis.SuffixMismatches,
            analysis.TransactionMismatches,
            analysis.ProtocolViolations,
            analysis.JoinedEligibleTransactions);
        analysis = analysis with { EligibilityOutcome = validity.EligibilityOutcome };

        return new AnticipationTransactionJoinFileReport(
            Path.GetFileName(path),
            after.Length,
            analyzedBytes,
            after.LastWriteTimeUtc,
            identity.AnalyzedSha256,
            identity.ObservedAfterSha256,
            identity.Stable,
            lineBoundary,
            validity.TechnicallyValid,
            "packaged_base_no_personal_dictionary_packs_or_exclusions",
            analysis);
    }

    internal static AnticipationTransactionJoinAnalysis Analyze(
        IEnumerable<string> lines,
        BenchmarkKnowledge knowledge,
        AutocorrectPolicySet policies)
    {
        int lineCount = 0;
        int parsedRuns = 0;
        int malformedRuns = 0;
        int spans = 0;
        int surfaceSwitches = 0;
        int terminalGestures = 0;
        int usableTimingGestures = 0;
        int noKnownPrecedingText = 0;
        int unusableTimingGestures = 0;
        int submittedTransactions = 0;
        int joinedEligibleTransactions = 0;
        int quarantinedBoundaryDisagreementTransactions = 0;
        int noTransactionSubmitted = 0;
        int knownBoundaryTerminalGestures = 0;
        int unknownBoundaryTerminalGestures = 0;
        int knownBoundaryNoTransactionSubmitted = 0;
        int unknownBoundaryNoTransactionSubmitted = 0;
        int suffixMismatches = 0;
        int transactionMismatches = 0;
        int protocolViolations = 0;
        int nonTerminalSubmissions = 0;
        int nonFirstTerminalSubmissions = 0;
        bool sentenceContinuityKnown = false;
        bool spanStartsAfterObservedEnter = false;
        string boundaryEvidence = "initial_unknown";
        string activeProcess = string.Empty;
        var span = new StringBuilder();
        var eligible = new List<EligibleTerminal>();
        var candidateCounts = new Dictionary<int, int>();
        var boundaryDisagreementReasons = new Dictionary<string, int>();
        var capture = new AggregateTransactionCaptureLane();
        using var session = new BenchmarkKeyboardSession(
            policies.Policy,
            knowledge.French,
            knowledge.English,
            probe: policies.AmbiguityProbe,
            wholeSentenceProbe: policies.WholeSentenceProbe,
            rerankLaneOverride: capture);
        session.BeginScenario();
        spans++;

        foreach (string line in lines)
        {
            lineCount++;
            if (!TryParseRun(line, out CapturedRun run))
            {
                malformedRuns++;
                ResetSpan(session, span, startsAfterObservedEnter: false);
                sentenceContinuityKnown = false;
                spanStartsAfterObservedEnter = false;
                boundaryEvidence = "malformed_run";
                activeProcess = string.Empty;
                spans++;
                continue;
            }

            parsedRuns++;
            if (activeProcess.Length > 0
                && !string.Equals(activeProcess, run.Process, StringComparison.OrdinalIgnoreCase))
            {
                surfaceSwitches++;
                ResetSpan(session, span, startsAfterObservedEnter: false);
                sentenceContinuityKnown = false;
                spanStartsAfterObservedEnter = false;
                boundaryEvidence = "process_change";
                spans++;
            }
            activeProcess = run.Process;

            for (int index = 0; index < run.Erased; index++)
                session.Backspace();
            bool boundaryWasKnownBeforeErasure = sentenceContinuityKnown;
            bool erasedBeyondObservedSpan = run.Erased > span.Length;
            if (erasedBeyondObservedSpan)
            {
                ResetSpan(session, span, startsAfterObservedEnter: false);
                sentenceContinuityKnown = false;
                spanStartsAfterObservedEnter = false;
                boundaryEvidence = "erased_beyond_observed_span";
                spans++;
            }
            else if (run.Erased == span.Length)
                span.Clear();
            else if (run.Erased > 0)
                span.Length -= run.Erased;
            if (!erasedBeyondObservedSpan)
            {
                sentenceContinuityKnown = spanStartsAfterObservedEnter
                    || ContainsTerminal(span);
                if (sentenceContinuityKnown)
                    boundaryEvidence = spanStartsAfterObservedEnter
                        ? "observed_enter"
                        : "observed_terminal";
                else if (boundaryWasKnownBeforeErasure && run.Erased > 0)
                    boundaryEvidence = "erased_last_observed_terminal";
            }

            int[]? gaps = ParseTiming(run.Timing, run.Text.Length);
            for (int index = 0; index < run.Text.Length; index++)
            {
                char current = run.Text[index];
                bool terminalStimulus = IsTerminal(current);
                bool firstTerminal = IsTerminal(current)
                    && (span.Length == 0 || !IsTerminal(span[^1]));
                int submitCallsBefore = capture.SubmitCalls;
                int summariesBefore = capture.Count;
                session.Type(current.ToString(), interKeyMs: 0);
                int submitDelta = capture.SubmitCalls - submitCallsBefore;
                int summaryDelta = capture.Count - summariesBefore;
                bool noCapture = submitDelta == 0 && summaryDelta == 0;
                bool oneClosedCapture = submitDelta == 1 && summaryDelta == 1;

                if (!firstTerminal)
                {
                    if (!noCapture)
                    {
                        protocolViolations++;
                        if (oneClosedCapture && terminalStimulus)
                            nonFirstTerminalSubmissions++;
                        else if (oneClosedCapture)
                            nonTerminalSubmissions++;
                    }
                    span.Append(current);
                    continue;
                }

                string boundaryEvidenceBeforeTerminal = boundaryEvidence;
                bool hadKnownSentenceBoundary = sentenceContinuityKnown;
                sentenceContinuityKnown = true;
                boundaryEvidence = "observed_terminal";
                terminalGestures++;
                if (hadKnownSentenceBoundary)
                    knownBoundaryTerminalGestures++;
                else
                    unknownBoundaryTerminalGestures++;
                bool knownPreceding = span.Length > 0;
                bool usableTiming = gaps is not null;
                if (!knownPreceding)
                    noKnownPrecedingText++;
                else if (!usableTiming)
                    unusableTimingGestures++;
                else
                    usableTimingGestures++;

                if (oneClosedCapture)
                {
                    submittedTransactions++;
                    AggregateTransactionSummary summary = capture[summariesBefore];
                    if (!summary.SemanticallyValid)
                    {
                        protocolViolations++;
                        span.Append(current);
                        continue;
                    }
                    if (!MatchesVisibleTransaction(
                            session.VisibleText,
                            summary.Literal,
                            current))
                    {
                        transactionMismatches++;
                        span.Append(current);
                        continue;
                    }
                    if (!hadKnownSentenceBoundary)
                    {
                        quarantinedBoundaryDisagreementTransactions++;
                        boundaryDisagreementReasons[boundaryEvidenceBeforeTerminal] =
                            boundaryDisagreementReasons.TryGetValue(
                                boundaryEvidenceBeforeTerminal,
                                out int boundaryCount)
                                ? boundaryCount + 1
                                : 1;
                        span.Append(current);
                        continue;
                    }
                    candidateCounts[summary.CandidateCount] =
                        candidateCounts.TryGetValue(summary.CandidateCount, out int count)
                            ? count + 1
                            : 1;
                    if (knownPreceding && usableTiming)
                    {
                        joinedEligibleTransactions++;
                        eligible.Add(new EligibleTerminal(current, gaps![index]));
                    }
                }
                else if (noCapture)
                {
                    noTransactionSubmitted++;
                    if (hadKnownSentenceBoundary)
                        knownBoundaryNoTransactionSubmitted++;
                    else
                        unknownBoundaryNoTransactionSubmitted++;
                }
                else
                    protocolViolations++;

                span.Append(current);
            }

            if (!ContinuesSpan(run.Closure))
            {
                bool startsAfterObservedEnter = run.Closure == "enter";
                ResetSpan(session, span, startsAfterObservedEnter);
                sentenceContinuityKnown = startsAfterObservedEnter;
                spanStartsAfterObservedEnter = startsAfterObservedEnter;
                boundaryEvidence = startsAfterObservedEnter
                    ? "observed_enter"
                    : "span_reset";
                spans++;
            }
        }

        int attributedSubmitCalls = submittedTransactions
            + nonTerminalSubmissions
            + nonFirstTerminalSubmissions
            + capture.HistoricalRequestCalls;
        if (capture.SubmitCalls != capture.ClosedRequestCalls + capture.HistoricalRequestCalls
            || capture.ClosedRequestCalls != capture.Count
            || capture.SubmitCalls != attributedSubmitCalls
            || capture.HistoricalRequestCalls != 0)
        {
            protocolViolations++;
        }

        suffixMismatches = session.InjectionFailureCount;
        BranchPolicyReport[] branches = CreateBranchReports(eligible);
        ReadinessReport[] readiness = CreateReadinessReports(eligible);

        return new AnticipationTransactionJoinAnalysis(
            lineCount,
            parsedRuns,
            malformedRuns,
            spans,
            surfaceSwitches,
            terminalGestures,
            usableTimingGestures,
            noKnownPrecedingText,
            unusableTimingGestures,
            submittedTransactions,
            joinedEligibleTransactions,
            quarantinedBoundaryDisagreementTransactions,
            noTransactionSubmitted,
            knownBoundaryTerminalGestures,
            unknownBoundaryTerminalGestures,
            knownBoundaryNoTransactionSubmitted,
            unknownBoundaryNoTransactionSubmitted,
            suffixMismatches,
            transactionMismatches,
            protocolViolations,
            nonTerminalSubmissions,
            nonFirstTerminalSubmissions,
            capture.SubmitCalls,
            capture.ClosedRequestCalls,
            capture.HistoricalRequestCalls,
            capture.InvalidClosedRequestCalls,
            "pending_prefix_validation",
            candidateCounts.OrderBy(static pair => pair.Key).ToDictionary())
        {
            Branches = branches,
            Readiness = readiness,
            BoundaryDisagreementReasons = boundaryDisagreementReasons
                .OrderBy(static pair => pair.Key)
                .ToDictionary(),
        };
    }

    internal static string ReplaceTerminal(string literal, char terminal)
    {
        if (literal.Length == 0 || !IsTerminal(literal[^1]) || !IsTerminal(terminal))
            throw new ArgumentException("A terminal branch requires one closed literal.");
        return literal[..^1] + terminal;
    }

    internal static bool MatchesVisibleTransaction(
        string visibleText,
        string transactionLiteral,
        char terminal) =>
        transactionLiteral.Length > 0
        && transactionLiteral[^1] == terminal
        && visibleText.EndsWith(transactionLiteral, StringComparison.Ordinal);

    internal static TypingStreamPrefixIdentity CreatePrefixIdentity(
        byte[] analyzed,
        byte[] observedAfter,
        bool lineBoundary)
    {
        string analyzedHash = Convert.ToHexString(SHA256.HashData(analyzed));
        string afterHash = Convert.ToHexString(SHA256.HashData(observedAfter));
        return new TypingStreamPrefixIdentity(
            analyzedHash,
            afterHash,
            lineBoundary && string.Equals(analyzedHash, afterHash, StringComparison.Ordinal));
    }

    internal static JoinValidity ClassifyValidity(
        bool prefixStable,
        int parsedRuns,
        int malformedRuns,
        int terminalGestures,
        int suffixMismatches,
        int transactionMismatches,
        int protocolViolations,
        int joinedEligibleTransactions)
    {
        bool technicallyValid = prefixStable
            && parsedRuns > 0
            && malformedRuns == 0
            && terminalGestures > 0
            && suffixMismatches == 0
            && transactionMismatches == 0
            && protocolViolations == 0;
        string eligibilityOutcome = !technicallyValid
            ? "invalid_run_no_eligibility_interpretation"
            : joinedEligibleTransactions == 0
                ? "valid_zero_eligible_observations"
                : "eligible_observations_present";
        return new JoinValidity(technicallyValid, eligibilityOutcome);
    }

    private static BranchPolicyReport[] CreateBranchReports(IReadOnlyList<EligibleTerminal> eligible)
    {
        int dots = eligible.Count(static item => item.Terminal == '.');
        return
        [
            new("terminal_oracle", eligible.Count, eligible.Count, 0, 0),
            new("dot_only", eligible.Count, dots, eligible.Count - dots, eligible.Count - dots),
            new("all_terminal", eligible.Count * TerminalBranches.Length, eligible.Count, 0,
                eligible.Count * (TerminalBranches.Length - 1)),
        ];
    }

    private static ReadinessReport[] CreateReadinessReports(
        IReadOnlyList<EligibleTerminal> eligible)
    {
        var reports = new List<ReadinessReport>();
        foreach (string policy in new[] { "terminal_oracle", "dot_only", "all_terminal" })
        {
            IEnumerable<EligibleTerminal> hits = policy == "dot_only"
                ? eligible.Where(static item => item.Terminal == '.')
                : eligible;
            EligibleTerminal[] hitArray = hits.ToArray();
            foreach (int trigger in TriggerDelaysMilliseconds)
            foreach (double decision in DecisionBudgetsMilliseconds)
            {
                double[] leads = hitArray
                    .Select(item => item.GapMilliseconds - trigger - decision)
                    .Where(static lead => lead > 0.0)
                    .ToArray();
                reports.Add(new ReadinessReport(
                    policy,
                    trigger,
                    decision,
                    hitArray.Length,
                    leads.Length,
                    hitArray.Length == 0 ? 0.0 : (double)leads.Length / hitArray.Length,
                    MetricDistribution.Create(leads)));
            }
        }
        return reports.ToArray();
    }

    private static void ResetSpan(
        BenchmarkKeyboardSession session,
        StringBuilder span,
        bool startsAfterObservedEnter)
    {
        session.BeginScenario(startsAfterObservedEnter);
        span.Clear();
    }

    private static bool TryParseRun(string line, out CapturedRun run)
    {
        run = default;
        try
        {
            using JsonDocument document = JsonDocument.Parse(line);
            JsonElement payload = document.RootElement.GetProperty("payload");
            run = new CapturedRun(
                payload.GetProperty("process").GetString() ?? string.Empty,
                payload.GetProperty("text").GetString() ?? string.Empty,
                payload.GetProperty("erased").GetInt32(),
                payload.GetProperty("closure").GetString() ?? string.Empty,
                payload.GetProperty("timing").GetString() ?? string.Empty);
            return run.Erased >= 0;
        }
        catch (JsonException) { return false; }
        catch (InvalidOperationException) { return false; }
        catch (KeyNotFoundException) { return false; }
        catch (FormatException) { return false; }
        catch (OverflowException) { return false; }
    }

    private static int[]? ParseTiming(string timing, int characterCount)
    {
        if (timing.Length == 0)
            return null;
        string[] parts = timing.Split(',');
        if (parts.Length != characterCount)
            return null;
        var result = new int[parts.Length];
        for (int index = 0; index < parts.Length; index++)
            if (!int.TryParse(parts[index], out result[index]) || result[index] < 0)
                return null;
        return result;
    }

    private static IEnumerable<string> ReadLines(byte[] utf8)
    {
        using var reader = new StringReader(Encoding.UTF8.GetString(utf8));
        while (reader.ReadLine() is { } line)
            yield return line;
    }

    private static byte[] ReadPrefix(string path, long byteCount)
    {
        if (byteCount > int.MaxValue)
            throw new ArgumentOutOfRangeException(nameof(byteCount));
        using var stream = new FileStream(
            path,
            FileMode.Open,
            FileAccess.Read,
            FileShare.ReadWrite | FileShare.Delete);
        if (stream.Length < byteCount)
            throw new EndOfStreamException();
        var bytes = new byte[(int)byteCount];
        stream.ReadExactly(bytes);
        return bytes;
    }

    private static bool IsTerminal(char value) => value is '.' or '!' or '?' or '…';
    internal static bool IsClosedTerminal(char value) => IsTerminal(value);

    private static bool ContainsTerminal(StringBuilder text)
    {
        for (int index = text.Length - 1; index >= 0; index--)
            if (IsTerminal(text[index]))
                return true;
        return false;
    }

    private static bool ContinuesSpan(string closure) => closure is "repair" or "cap";

    private readonly record struct CapturedRun(
        string Process,
        string Text,
        int Erased,
        string Closure,
        string Timing);

    private readonly record struct EligibleTerminal(char Terminal, int GapMilliseconds);
}

internal sealed class AggregateTransactionCaptureLane : IRerankLane
{
    private readonly List<AggregateTransactionSummary> _captured = new();

    public int Count => _captured.Count;

    public int SubmitCalls { get; private set; }

    public int ClosedRequestCalls { get; private set; }

    public int HistoricalRequestCalls { get; private set; }

    public int InvalidClosedRequestCalls { get; private set; }

    public AggregateTransactionSummary this[int index] => _captured[index];

    public Action<RerankResult>? ResultSink { get; set; }

    public void Submit(RerankRequest request)
    {
        SubmitCalls++;
        if (request is ClosedSentenceRerankRequest closed)
        {
            ClosedRequestCalls++;
            ClosedSentenceTransaction transaction = closed.Transaction;
            bool semanticallyValid = IsSemanticallyValid(transaction);
            if (!semanticallyValid)
                InvalidClosedRequestCalls++;
            _captured.Add(new AggregateTransactionSummary(
                transaction.Literal,
                transaction.Words.Count,
                1 + transaction.Edits.Count,
                semanticallyValid));
        }
        else
        {
            HistoricalRequestCalls++;
        }
        ResultSink?.Invoke(new RerankResult(
            SlotIndex: -1,
            Epoch: request.Epoch,
            Outcome: RerankOutcome.Abstained(RerankOutcome.AbstainReasons.NoRule)));
    }

    public void Dispose() { }

    private static bool IsSemanticallyValid(ClosedSentenceTransaction transaction)
    {
        if (transaction.Literal.Length == 0
            || !AnticipationTransactionJoinCommand.IsClosedTerminal(transaction.Literal[^1])
            || transaction.Words.Count == 0
            || transaction.Edits.Count == 0)
        {
            return false;
        }

        foreach (SentenceEditCandidate edit in transaction.Edits)
        {
            if (edit.SlotIndex < 0
                || edit.SlotIndex >= transaction.Words.Count
                || edit.Start < 0
                || edit.Length <= 0
                || edit.Start > transaction.Literal.Length - edit.Length
                || edit.Replacement.Length == 0)
            {
                return false;
            }
        }
        return true;
    }
}

internal readonly record struct AggregateTransactionSummary(
    string Literal,
    int WordCount,
    int CandidateCount,
    bool SemanticallyValid);

internal readonly record struct TypingStreamPrefixIdentity(
    string AnalyzedSha256,
    string ObservedAfterSha256,
    bool Stable);

internal readonly record struct JoinValidity(
    bool TechnicallyValid,
    string EligibilityOutcome);

internal sealed record AnticipationTransactionJoinFileReport(
    string SourceFile,
    long SourceFileBytes,
    long AnalyzedBytes,
    DateTime SourceLastWriteUtc,
    string AnalyzedSha256,
    string ObservedAfterSha256,
    bool AnalyzedPrefixStable,
    bool PrefixEndedAtLineBoundary,
    bool TechnicallyValid,
    string LexicalConfiguration,
    AnticipationTransactionJoinAnalysis Replay);

internal sealed record AnticipationTransactionJoinAnalysis(
    int LineCount,
    int ParsedRuns,
    int MalformedRuns,
    int Spans,
    int SurfaceSwitches,
    int FirstTerminalGestures,
    int UsableTimingGestures,
    int NoKnownPrecedingTextGestures,
    int UnusableTimingGestures,
    int SubmittedTransactions,
    int JoinedEligibleTransactions,
    int QuarantinedBoundaryDisagreementTransactions,
    int NoTransactionSubmitted,
    int KnownBoundaryTerminalGestures,
    int UnknownBoundaryTerminalGestures,
    int KnownBoundaryNoTransactionSubmitted,
    int UnknownBoundaryNoTransactionSubmitted,
    int SuffixMismatches,
    int TransactionMismatches,
    int ProtocolViolations,
    int NonTerminalSubmissions,
    int NonFirstTerminalSubmissions,
    int LaneSubmitCalls,
    int LaneClosedRequestCalls,
    int LaneHistoricalRequestCalls,
    int LaneInvalidClosedRequestCalls,
    string EligibilityOutcome,
    IReadOnlyDictionary<int, int> JoinedCandidateCountHistogram)
{
    public IReadOnlyList<BranchPolicyReport> Branches { get; init; } = [];
    public IReadOnlyList<ReadinessReport> Readiness { get; init; } = [];
    public IReadOnlyDictionary<string, int> BoundaryDisagreementReasons { get; init; } =
        new Dictionary<string, int>();
}

internal sealed record BranchPolicyReport(
    string Policy,
    int ScoringJobs,
    int ExactHits,
    int BranchMisses,
    int WastedJobs);

internal sealed record ReadinessReport(
    string Policy,
    int TriggerDelayMilliseconds,
    double DecisionMilliseconds,
    int EligibleHits,
    int ReadyBeforeTerminal,
    double ReadyRate,
    MetricDistribution PositiveLeadMilliseconds);
