using System.IO;
using System.IO.Compression;
using System.Text;

namespace Deckle.Autocorrect;

// ── VerbMorphology ────────────────────────────────────────────────────────────
//
// The morphological knowledge the grammar stage reasons over: for a verb surface
// form, which verb it is (lemma = the infinitive) and the mode/tense/person it
// realises; and, in reverse, the single form a lemma takes at a given
// mode/tense/person. Derived from Lexique 3.83's verb rows (cgram VER/AUX),
// regenerated by build-data alongside the frequency lexicon — see LexiconBuilder.
//
// Two readings of the same surface (manges = manger ind:pre:2s AND sub:pre:2s)
// are both kept: the grammar stage weighs the whole set, never a single guess.
// A form Lexique also tags as something other than a verb (cgramortho carries a
// NOM/ADJ/…: "ferme" is fermer-the-verb but also a noun) is marked ambiguous —
// the strict agreement rule stands aside on those, the conservative default.
//
// Person-number is Lexique's compact code: 1s,2s,3s,1p,2p,3p — empty for forms
// that have none (the infinitive "inf", the participles "par:pas"/"par:pre").
public sealed class VerbMorphology
{
    // form (lowercased, NFC) → its verb readings, in source order.
    private readonly Dictionary<string, List<VerbReading>> _byForm;

    // Forms carrying a non-verb reading too (cgramortho is not VER/AUX only).
    private readonly HashSet<string> _ambiguous;

    // (lemma, mode, tense, person-number) → the surface form, when exactly one
    // form fills that slot. A slot two distinct forms fill is dropped, never
    // guessed: synthesis must be unique to be safe.
    private readonly Dictionary<ConjugationSlot, string> _synth;

    private VerbMorphology(
        Dictionary<string, List<VerbReading>> byForm,
        HashSet<string> ambiguous,
        Dictionary<ConjugationSlot, string> synth,
        int skippedLines)
    {
        _byForm = byForm;
        _ambiguous = ambiguous;
        _synth = synth;
        SkippedLines = skippedLines;
    }

    // Lines that could not be parsed (wrong field count, malformed). Skipped
    // silently but counted — a data-quality signal for build-data.
    public int SkippedLines { get; }

    public int Count => _byForm.Count;

    // The verb readings of a form, empty when the form is no verb at all. The
    // caller must pass a lowercased form (the store is keyed lowercase).
    public IReadOnlyList<VerbReading> Analyses(string lowerForm) =>
        _byForm.TryGetValue(lowerForm, out List<VerbReading>? readings)
            ? readings
            : Array.Empty<VerbReading>();

    public bool IsVerb(string lowerForm) => _byForm.ContainsKey(lowerForm);

    // The form also carries a non-verb reading (noun, adjective, …) somewhere in
    // the lexicon — the agreement rule never rewrites these.
    public bool IsAmbiguous(string lowerForm) => _ambiguous.Contains(lowerForm);

    // The surface form a lemma takes at this exact mode/tense/person, or null
    // when no form fills the slot or more than one does (ambiguous → unsafe).
    public string? Conjugate(string lemma, string mode, string tense, string personNumber) =>
        _synth.TryGetValue(new ConjugationSlot(lemma, mode, tense, personNumber), out string? form)
            ? form
            : null;

    // Reads `form<TAB>lemma<TAB>infover<TAB>verbOnly` lines, UTF-8. '#'-prefixed
    // and blank lines are comments; malformed lines are skipped (and counted).
    // infover is the raw Lexique codes (mode:tense:person, ';'-separated);
    // verbOnly is "1" when the form is a verb form only, "0" when it doubles as
    // another part of speech.
    public static VerbMorphology LoadTsv(TextReader reader)
    {
        var byForm = new Dictionary<string, List<VerbReading>>(StringComparer.Ordinal);
        var ambiguous = new HashSet<string>(StringComparer.Ordinal);
        var synth = new Dictionary<ConjugationSlot, string>();
        var synthClash = new HashSet<ConjugationSlot>();
        int skipped = 0;

        string? line;
        while ((line = reader.ReadLine()) is not null)
        {
            if (line.Length == 0 || line[0] == '#')
                continue;

            string[] f = line.Split('\t');
            if (f.Length < 4)
            {
                skipped++;
                continue;
            }

            string form = f[0].ToLowerInvariant().Normalize(NormalizationForm.FormC);
            string lemma = f[1];
            if (form.Length == 0 || lemma.Length == 0)
            {
                skipped++;
                continue;
            }

            if (f[3] == "0")
                ambiguous.Add(form);

            if (!byForm.TryGetValue(form, out List<VerbReading>? readings))
                byForm[form] = readings = new List<VerbReading>();

            foreach (VerbReading reading in ParseInfover(lemma, f[2]))
            {
                readings.Add(reading);

                // Build the reverse slot — but only for forms that carry a
                // person-number (the conjugated cells synthesis ever targets).
                if (reading.PersonNumber.Length == 0)
                    continue;
                var slot = new ConjugationSlot(lemma, reading.Mode, reading.Tense, reading.PersonNumber);
                if (synthClash.Contains(slot))
                    continue;
                if (synth.TryGetValue(slot, out string? prior))
                {
                    if (prior != form) { synth.Remove(slot); synthClash.Add(slot); }
                }
                else
                {
                    synth[slot] = form;
                }
            }
        }

        return new VerbMorphology(byForm, ambiguous, synth, skipped);
    }

    // The shipped artifact is gzip-compressed; decompress on the way in.
    public static VerbMorphology LoadTsvGz(string path)
    {
        using var file = File.OpenRead(path);
        using var gz = new GZipStream(file, CompressionMode.Decompress);
        using var reader = new StreamReader(gz, Encoding.UTF8);
        return LoadTsv(reader);
    }

    // Expands a Lexique infover field ("ind:pre:1s;ind:pre:3s;") into one reading
    // per code, all sharing the lemma. A code is mode[:tense[:person]] — the
    // infinitive ("inf") and participles ("par:pas") carry fewer parts; missing
    // parts read as empty. Malformed codes are dropped, not guessed.
    private static IEnumerable<VerbReading> ParseInfover(string lemma, string infover)
    {
        foreach (string code in infover.Split(';', StringSplitOptions.RemoveEmptyEntries))
        {
            string[] parts = code.Split(':');
            string mode = parts[0];
            if (mode.Length == 0)
                continue;
            string tense = parts.Length > 1 ? parts[1] : "";
            string person = parts.Length > 2 ? parts[2] : "";
            yield return new VerbReading(lemma, mode, tense, person);
        }
    }
}

// One morphological reading of a verb surface form: which verb (lemma = the
// infinitive), and the mode/tense/person-number it realises.
public readonly record struct VerbReading(string Lemma, string Mode, string Tense, string PersonNumber);

// A reverse-synthesis key: the cell a lemma's paradigm fills at a mode/tense/
// person-number.
internal readonly record struct ConjugationSlot(string Lemma, string Mode, string Tense, string PersonNumber);
